### ISSUE TITLE
Search results are illegible

### ISSUE THREAD

**Issue by smockle** [davidleininger/cobaltnext-vscode#1]
I really like this theme—thank you for your work on it!

I noticed a minor issue in the search pane:
![1](https://user-images.githubusercontent.com/3104489/33043437-52111850-cdfa-11e7-8057-7b866c70d132.png)

For comparison, here is Cobalt2:
![1b](https://user-images.githubusercontent.com/3104489/33043640-f8c8ea60-cdfa-11e7-93eb-5f263720352b.png)

**Comment by davidleininger** [comment]
Thanks for the kind words! I fixed this issue in the most recent update 0.0.12. Hope that helps.
