### ISSUE TITLE
More Italic version

### ISSUE THREAD

**Issue by seanonthenet** [davidleininger/cobaltnext-vscode#10]
Awesome theme. Love it. Would be great if there was a version option with more Operator Mono italics for all the language keywords 

eg:
const, let, class, return, this, if, else, &&, ||, import, as, from, export, default....

...etc

kind of like the "[Fantastic](https://marketplace.visualstudio.com/items?itemName=sldobri.daily)" theme has an option for.

**Comment by davidleininger** [comment]
I'll work on this. Thanks for the idea.
