### ISSUE TITLE
Ignored files (in file explorer pane) are red

### ISSUE THREAD

**Issue by smockle** [davidleininger/cobaltnext-vscode#2]
Would you consider a different color? To me, red signifies deleted/error states.
![2](https://user-images.githubusercontent.com/3104489/33043510-90bf724a-cdfa-11e7-88ae-00cded2bf36f.png)

For comparison, here is Cobalt2:
![2b](https://user-images.githubusercontent.com/3104489/33043584-ce40888e-cdfa-11e7-8a92-34a02de598cb.png)

**Comment by davidleininger** [comment]
Fixed in version 0.0.12
