### ISSUE TITLE
Terminal's ansiBlack and ansiBrightBlack are not visible on the background

### ISSUE THREAD

**Issue by pq9x** [davidleininger/cobaltnext-vscode#22]
First of all, the theme is awesome. Love it!

However, PowerShell is using ansiBrightBlack which make it barely visible on the background. Please see the attached screenshot.

![Annotation 2020-03-09 192131](https://user-images.githubusercontent.com/52546124/76284769-6688aa80-625b-11ea-92d9-0d653f07da3e.png)

Below is what I'm overriding for the time being.

```json
    "workbench.colorCustomizations": {
        "terminal.ansiBlack": "#696969",
        "terminal.ansiBrightBlack": "#696969"
    }
```

**Comment by davidleininger** [comment]
@Kongdivin I’ll cut an update tomorrow. Thanks for pointing that out for me.

**Comment by davidleininger** [comment]
About to merge in the updated colors, here's the new look. If you haven't tried the Dark version of the theme, give it a spin. I've been using it for the last few weeks, and I tend to like it a lot more.

### Original Theme
![image](https://user-images.githubusercontent.com/1840132/77258280-a716f980-6c47-11ea-9e5f-2ff79a8cd311.png)

### Dark Theme
![image](https://user-images.githubusercontent.com/1840132/77258302-c4e45e80-6c47-11ea-9548-a965fa43f5c9.png)
