### ISSUE TITLE
Diff editor is hard to read due to each line having a border

### ISSUE THREAD

**Issue by vladimir-djokic** [davidleininger/cobaltnext-vscode#33]
When using this color theme, diff editor shows outline (border) for each line that has been removed or added, making the text hard to read:

![Screenshot 2022-07-25 002756](https://user-images.githubusercontent.com/16443718/180668361-f2b1f534-47c4-4e68-92aa-96fe148a2d37.png)

Let me know if you need any additional information from my side.

**Comment by davidleininger** [comment]
I’ll take a look at this and see if there is anything I can do.

**Comment by davidleininger** [comment]
@vladeck, Which version of the theme are you using? Regular, Dark, or Minimal?

**Comment by davidleininger** [comment]
@vladeck how is this?
![image](https://user-images.githubusercontent.com/1840132/188054873-2368a58c-fc7f-4033-9a79-24914fa26fa6.png)

**Comment by vladimir-djokic** [comment]
@davidleininger It was regular Cobalt and the the last screenshot looks incredible!

**Comment by davidleininger** [comment]
@vladeck Great. I'll get this pushed up with a new version today.
