### ISSUE TITLE
Incorrect colors in git conflicts

### ISSUE THREAD

**Issue by epszaw** [davidleininger/cobaltnext-vscode#4]
![image](https://user-images.githubusercontent.com/13414205/39392851-29d072a2-4ac6-11e8-8bf9-3e93a0ed1686.png)

But in diff mode -- working.

**Comment by davidleininger** [comment]
Thanks for adding an issue. This has been fixed and pushed to the marketplace.

**Comment by epszaw** [comment]
@davidleininger thank you! :raised_hands:
