### ISSUE TITLE
Incorrect search behavior

### ISSUE THREAD

**Issue by justlstn** [davidleininger/cobaltnext-vscode#6]
- VSCode Version: 1.27.2
- OS Version: Windows 10 Pro (1803)
- OS build 17134.285

Steps to Reproduce:

1. Open some large project;
2. Switch to search tab and type something like "h";
3. If amount of results greater than or equal to 10000 you can see the bug;

![shot_180914_131425](https://user-images.githubusercontent.com/10776006/45545053-c4346600-b821-11e8-871f-ed38af29ca5b.png)

Does this issue occur when all extensions are disabled?: No

P.S. When I switch to another theme for example "Dark (Visual Studio)" the issue doesn't occur

**Comment by davidleininger** [comment]
Thanks for the heads up. Just fixed and pushed the update.
